### ISSUE TITLE
Identify more training data sources

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/training-data#1]
We currently have:
- stacksgov/sips repo
- hirosystems/docs repo
- stacks-network/docs repo
- coinfabrik audits (2024)

What else should we add?

**Comment by whoabuddy** [comment]
Add smart contracts repo from boom. (250gb?)

@moodmosaic has a curated version from fuzzing.

**Comment by moodmosaic** [comment]
We could also add https://github.com/stacks-network/clarity-wasm/tree/main/clar2wasm/tests/contracts.

**Comment by whoabuddy** [comment]
Linking this issue as the idea overlaps:
- aibtcdev/agent-tools-ts#2

**Comment by whoabuddy** [comment]
Style guides seem like something we want to document as well, AirBnB uses [this one for example](https://github.com/airbnb/javascript).

**Comment by whoabuddy** [comment]
Anthropic has a great course on using their LLMs here, content like this would be super helpful too:
https://github.com/anthropics/courses/tree/master

Might be worth breaking some of these out into smaller issues? What's the actionable next step(s)?

**Comment by whoabuddy** [comment]
Clarity book too!

**Comment by whoabuddy** [comment]
Migrated items listed into this issue into separate issues as action items. Closing this one out!
